"""autogenerate

Revision ID: db747850aaf6
Revises: 63e9ff0fa03a
Create Date: 2026-02-21 19:28:22.260349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db747850aaf6'
down_revision: Union[str, Sequence[str], None] = '63e9ff0fa03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referals', 'ref_tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('vpn_accounts', sa.Column('vpn_tg_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'vpn_accounts', ['vpn_tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vpn_accounts', type_='unique')
    op.drop_column('vpn_accounts', 'vpn_tg_id')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('referals', 'ref_tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
